### ISSUE TITLE
Limit and Offset

### ISSUE THREAD

**Issue by williamkibira** [absent1706/sqlalchemy-mixins#11]
Is there a way to do limits and offsets in sql query mixins ?

**Comment by absent1706** [comment]
Hi! What do you mean under "doing limits and offsets"?
Code like 

```
User.query
```

or 

```
User.where(somefield=somevalue)
```

Returns reqular SQLAlchemy `Query` object which has `limit` and `offset` methods

**Comment by williamkibira** [comment]
Ow, i did not take not of that , sorry for the bother .
