### ISSUE TITLE
Releases not appearing in GitHub?

### ISSUE THREAD

**Issue by antgel** [absent1706/sqlalchemy-mixins#19]
Great to see the activity here. `pip list --outdated` shows that I can upgrade from 0.2.3 to 1.1. However, https://github.com/absent1706/sqlalchemy-mixins/releases doesn't show that (although the Tags tab does).

**Comment by absent1706** [comment]
Thanks, I added the release.
https://github.com/absent1706/sqlalchemy-mixins/releases/tag/v1.1
