### ISSUE TITLE
FEATURE: add SerializeMixin with to_dict() method

### ISSUE THREAD

**Issue by absent1706** [absent1706/sqlalchemy-mixins#2]

**Comment by absent1706** [comment]
see https://gist.github.com/mjhea0/9b9c400a2bc58e6c90e5f77eeb739d6b

**Comment by Kalki5** [comment]
Hi,
Any update on this?
If not, I'd be glad to make a PR along with some other additional features?

**Comment by absent1706** [comment]
Hi!
Sadly, I have no time to work on this.
Feel free to make any PR's :)
Thank you!

**Comment by absent1706** [comment]
Made in https://github.com/absent1706/sqlalchemy-mixins/releases/tag/v1.1
