### ISSUE TITLE
could Pagination be added？

### ISSUE THREAD

**Issue by scil** [absent1706/sqlalchemy-mixins#28]
I love sqlalchemy-mixins as a user of Laravel.

Hope it can add Pagination like
- [sqlakeyset](https://github.com/djrobstep/sqlakeyset)
- [active-alchemy](https://github.com/mardix/active-alchemy#pagination) 
- [paginate_sqlalchemy](https://github.com/Pylons/paginate_sqlalchemy) 
- [SQLA-Wrapper](https://jpscaletti.com/sqla-wrapper/pagination.html#pagination)

**Comment by kor0p** [comment]
you can use paginate_sqlalchemy by creating class method for your base class, as I do it just now. Thanks for your comment))

**Comment by scil** [comment]
Thank you.

Please let me add on more 
- [ahmadjavedse/sqlalchemy-paginator](https://github.com/ahmadjavedse/sqlalchemy-paginator). The lastest branch is [exhuma/sqlalchemy-paginator](https://github.com/exhuma/sqlalchemy-paginator/tree/integration)
