### ISSUE TITLE
MySQL DB update

### ISSUE THREAD

**Issue by andrey-bm52** [absent1706/sqlalchemy-mixins#33]
Need to add commit() statement to save() function in activerecord.py module:
def save(self):
        """Saves the updated model to the current entity db.
        """
        self.session.add(self)
        self.session.flush()
        self.session.commit()     # save in MySQL
        return self

**Comment by absent1706** [comment]
Hi @andrey-bm52!
It was not made intentionally to not affect SQLAlchemy/DataMapper pattern philosophy.
If you need to make commit automatically, consider enabling  autocommit https://docs.sqlalchemy.org/en/13/orm/session_api.html
