### ISSUE TITLE
Latest release not pushed to archive

### ISSUE THREAD

**Issue by yusufnb** [absent1706/sqlalchemy-mixins#35]
Hi, trying to install this via pipenv which still get the v1.1. I see there have been upgrades since then but pip is not able to get them. Can you please update?

**Comment by absent1706** [comment]
Hi!
You can use v1.2.1 release. 

Also note that 1.1 release was deleted from PyPi (see why at https://github.com/absent1706/sqlalchemy-mixins/issues/37) , just use 1.0.1 instead of you dont want to update to 1.2.1. 

Thanks!
