### ISSUE TITLE
When will next version be released? Current is 1.2.1

### ISSUE THREAD

**Issue by carloshanson** [absent1706/sqlalchemy-mixins#43]
The SerializeMixin in version 1.2.1 does not include `hybrid_attributes` in `to_dict()`.

I have cloned the repo and built from source, but I would prefer not to maintain that.

When will the next version be released?

Thanks. Carlos

**Comment by maximdeclercq** [comment]
As a workaround to building from source, you can put `git+git://github.com/absent1706/sqlalchemy-mixins` inside requirements.txt until the next version is released. This would make pip install it from source.

**Comment by michaelbukachi** [comment]
Hello, we've just released v1.3. I'm closing this issue.
