### ISSUE TITLE
contains_eager issues

### ISSUE THREAD

**Issue by fredludlow** [absent1706/sqlalchemy-mixins#64]
The smart_query method is quite clever and uses `contains_eager` where it can to avoid duplicating joins. It does this by adding a contains_eager option for every entity it visits:

https://github.com/absent1706/sqlalchemy-mixins/blob/fdb0256ad2b57084b802e95bc71c3c19b354d5c3/sqlalchemy_mixins/smartquery.py#L112-L117

Then when applying the options from the `schema` argument, it skips those which were already visited

https://github.com/absent1706/sqlalchemy-mixins/blob/fdb0256ad2b57084b802e95bc71c3c19b354d5c3/sqlalchemy_mixins/smartquery.py#L146-L151

There are a couple of issues with this:

1) There's a disabled test (test_override_eagerload_method_in_schema) with a TODO comment. This checks that the following statement should execute 2 DB commands, but in fact it issues 1:
```python
        res = Comment.smart_query(
            filters=dict(post___public=True, post___user___name__like='Bi%'),
            schema={
                'post': SUBQUERY
            }
        ).all()
```

That is - the `SUBQUERY` join specified in `schema` isn't being performed because the `post` table has already been visited and `contains_eager` has been applied.

For maybe 99% of cases the practical result is the same, *but*

2) Using `contains_eager` means you take responsibility for loading the contents of a collection, see
https://docs.sqlalchemy.org/en/13/orm/loading_relationships.html#using-contains-eager-to-load-a-custom-filtered-collection-result

An example would be (based on the test-cases in test_smartquery):

```python
res = User.smart_query(
            filters=dict(posts___archived=True)
        ).all()
```
This returns a single user (`Bill u1`) which is correct, and his `posts` relationship contains just the single archived post. There are actually 2 posts for this user in the database but by using contains_eager we have taken control of how the `posts` collection is loaded and only 1 is visible. 

There's a bit of a question here about what the correct behaviour is, and there's a possibility that changing this will break things. 

I think the optimal strategy would be something like

1. Track all visited entities/aliases which could be candidates for `contains_eager` option
2. If they don't have an explicit entry in the schema dict then call `contains_eager`, else do the thing requested in `schema`.

This looks like the behaviour that the disabled test was coded against, but if you have existing code it may return extra objects (which might be a security concern if, for example the filter is used to implement permissions on objects).

My quick workaround for this is to add another parameter to smart_query: `separate_eager_load` which defaults to `False` for current behaviour but if `True` simply skips any call to `contains_eager` - this breaks the automatic eager-loading detection so you have to fully specify schema.

Apologies for the long write-up - any thoughts on this much appreciated

**Comment by michaelbukachi** [comment]
Hey, @fredludlow  thanks for the detailed explanation. Haha, The longer the better! 
Hmm, instead of adding a parameter we can just detect the presence of `SUBQUERY` joins and use that as our condition for enabling, disabling `contains_eager`

**Comment by fredludlow** [comment]
Thanks @michaelbukachi 

Agree we should avoid the extra parameter.

If we go with just looking for `SUBQUERY` then we'd get different behaviour (different number of posts for user 1 in the example query above) depending on whether we used  `JOINED` or  `SUBQUERY` which also doesn't seem quite right to me..? (i.e. `SUBQUERY` would retrieve all the posts, but `JOINED` would fallback to `contains_eager` and show the filtered set).

I think if we detected either `SUBQUERY` or `JOINED` it would behave better, but my concern was breaking other people's code that relies on the current behaviour, but maybe I'm looking at a really specific case here and it won't make much difference to anyone else (or we could bump the major version number to indicate possibly breaking change). If you don't think it's a problem then happy to make a PR that does this.

**Comment by michaelbukachi** [comment]
@fredludlow Maybe we can explore this further. The ideal scenario would be to modify the implementation without affecting the users. So we have the same syntax as before but internally it works differently. I will look into this over the weekend and experiment with different approaches. If we are not able to come with a solution, then we can introduce a breaking change in the next major release.

**Comment by fredludlow** [comment]
Sounds great, thanks for looking at it!
