### ISSUE TITLE
SqlAlchemy 1.4 deprecation warning

### ISSUE THREAD

**Issue by rafa761** [absent1706/sqlalchemy-mixins#81]
Hi 

With SqlAlchemy 1.4 it's possible to test if the code will work with future SqlAlchemy 2.0

https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings

using this we receive some deprecation warnings from sqlalchemy-mixins

sqlalchemy==1.4.23
sqlalchemy-mixins==1.5

![image](https://user-images.githubusercontent.com/41598843/132744023-a44d1ff5-dfc6-4e5f-8f26-8bdf6e870a80.png)

**Comment by michaelbukachi** [comment]
Hi,

Thanks for noting this. Do you mind opening a PR that adds CI tests against 2.0?
