### ISSUE TITLE
Imperative mode

### ISSUE THREAD

**Issue by lucasvazq** [absent1706/sqlalchemy-mixins#92]
Is there the possibility of using this library in an imperative way?

Here is an example that show how I usually define my tables:
```py
from sqlalchemy import Column, Integer, Table
from sqlalchemy.orm import registry

class MyTable:
    id: int

mapper_registry = registry()

table_name = 'my_table'

columns = [
    Column("id", Integer, primary_key=True),
]

table = Table(
    table_name,
    mapper_registry.metadata,
    *columns,
)

mapper_registry.map_imperatively(MyTable, table)
```

Changing the imperative mode is a bit difficult for me because of how the whole project is structured and because of its size. Each of the parts of this example are typically in separate files.

Any kind of help anyone can offer is a great light for me because I really want to incorporate the `SmartQueryMixin` 🙏.

**Comment by michaelbukachi** [comment]
@lucasvazq The library was heavily built around the ORM. I don't think it will be easy to adapt it to use an imperative approach.

**Comment by lucasvazq** [comment]
@michaelbukachi Okay!!
Thanks for the reply!! I am relieved to know whether or not there is a way.
I was also thinking of copying this idea but making it from scratch and according to our needs (it would really be very little code).
