### ISSUE TITLE
Adapt to sqlalchemy 2.0?

### ISSUE THREAD

**Issue by rehth** [absent1706/sqlalchemy-mixins#93]
As title

**Comment by michaelbukachi** [comment]
@rehth Plans for this are already underway.

**Comment by rehth** [comment]
ok thx

**Comment by michaelbukachi** [comment]
@rehth Please test #95

**Comment by rehth** [comment]
> @rehth Please test #95

I used it for a while. I haven't found any problems yet. It's great
